const fs = require('fs');

const path = 'src/locales/vi.json';
const viData = JSON.parse(fs.readFileSync(path, 'utf8'));

viData.lineMachine = {
  title: "Quản lý Line & Machine",
  subtitle: "Quản lý dây chuyền và máy móc",
  addLine: "Thêm Line",
  addMachine: "Thêm Máy",
  copyMachine: "Sao chép Máy",
  totalLine: "Tổng số Line",
  totalMachine: "Tổng số Máy",
  search: "Tìm kiếm",
  searchPlaceholder: "Nhập tên line, máy...",
  area: "Khu vực",
  all: "Tất cả",
  loading: "Đang tải dữ liệu...",
  noData: "Không có dữ liệu",
  noDataHint: "Chưa có dữ liệu line, hãy thêm line mới",
  lineListTitle: "Danh sách Line",
  expandAll: "Mở rộng tất cả",
  collapseAll: "Thu gọn tất cả",
  viewDetailsShort: "Chi tiết",
  addMachineShort: "Thêm Máy",
  copy: "Sao chép",
  edit: "Sửa",
  delete: "Xóa",
  table: {
    machineName: "TÊN MACHINE",
    actions: "THAO TÁC",
    noMachines: "Chưa có máy nào trong line này."
  },
  analytics: {
    button: "Thống kê",
    title: "Thống kê vật tư theo Machine",
    fromDate: "Từ ngày",
    toDate: "Đến ngày",
    apply: "Lọc",
    reset: "Xóa lọc",
    colItemName: "Tên vật tư",
    colArea: "Xưởng",
    colStock: "Tồn kho",
    colUsed: "Đã sử dụng",
    colOrderCount: "Số lần order",
    loading: "Đang phân tích dữ liệu...",
    empty: "Không có dữ liệu sử dụng vật tư.",
    loadError: "Lỗi tải thống kê"
  },
  modal: {
    addLine: "Thêm Line mới",
    editLine: "Sửa Line",
    addLineHint: "Tạo line mới cho xưởng",
    editLineHint: "Cập nhật thông tin line",
    close: "Đóng",
    lineName: "Tên Line",
    lineNamePlaceholder: "Nhập tên line...",
    area: "Xưởng (Area Part)",
    cancel: "Hủy",
    saving: "Đang lưu...",
    save: "Lưu",
    addMachine: "Thêm Machine",
    editMachine: "Sửa Machine",
    machineHint: "Chọn line chứa machine. Có thể chuyển machine sang line khác.",
    machineName: "Tên Machine",
    machineNamePlaceholder: "Nhập tên machine...",
    belongsToLine: "Thuộc Line",
    managementCode: "Mã quản lý",
    managementCodePlaceholder: "Nhập mã quản lý...",
    modelMachine: "Model máy",
    modelMachinePlaceholder: "Nhập model máy...",
    seriNumber: "Số Seri",
    seriNumberPlaceholder: "Nhập số seri...",
    dateInput: "Ngày nhập"
  },
  copyModal: {
    title: "Sao chép danh sách Machine",
    hint: "Sao chép máy từ line này sang line khác",
    sourceLine: "Line nguồn",
    machinesSuffix: "máy",
    selecting: "Đang chọn",
    machineUnit: "máy",
    copyListTitle: "Danh sách sao chép",
    noSourceMachines: "Không có máy nào",
    summary: "Tổng quan",
    copyFrom: "Từ:",
    to: "Đến:",
    targetLinesSuffix: "line đích",
    newMachinesEstimate: "máy mới sẽ được tạo",
    targetLine: "Line đích",
    targetLineHint: "Chọn một hoặc nhiều line đích",
    selectAll: "Chọn tất cả",
    clearSelection: "Bỏ chọn",
    copying: "Đang sao chép...",
    copyAction: "Tiến hành sao chép"
  },
  confirmModal: {
    cancel: "Hủy",
    deleting: "Đang xóa...",
    delete: "Xóa"
  },
  deleteConfirm: {
    noSourceLine: "Không tìm thấy line nguồn.",
    confirmLineNoMachines: "Bạn có chắc chắn muốn xóa line này?",
    confirmMachineMessage: "Bạn có chắc chắn muốn xóa máy này?"
  },
  toast: {
    loadErrorTitle: "Lỗi tải dữ liệu",
    loadErrorDetail: "Có lỗi khi tải danh sách line và machine.",
    notRefreshedTitle: "Lỗi làm mới",
    notRefreshedDetail: "Không thể làm mới dữ liệu.",
    missingInfoTitle: "Thiếu thông tin",
    missingLineName: "Vui lòng nhập tên line.",
    missingLineIdTitle: "Lỗi ID",
    missingLineIdDetail: "Không tìm thấy ID của line.",
    addLineSuccessTitle: "Thêm line thành công",
    updateLineSuccessTitle: "Cập nhật line thành công",
    addLineFailTitle: "Lỗi thêm line",
    updateLineFailTitle: "Lỗi cập nhật line",
    checkInfoRetry: "Vui lòng kiểm tra lại thông tin.",
    noLineTitle: "Không tìm thấy line",
    noLineDetail: "Không thể xác định line cần thêm.",
    missingMachineName: "Vui lòng nhập tên máy.",
    missingLineSelect: "Vui lòng chọn line.",
    missingMachineIdTitle: "Lỗi ID",
    missingMachineIdDetail: "Không tìm thấy ID của máy.",
    addMachineSuccessTitle: "Thêm máy thành công",
    updateMachineSuccessTitle: "Cập nhật máy thành công",
    addMachineFailTitle: "Lỗi thêm máy",
    updateMachineFailTitle: "Lỗi cập nhật máy",
    notEnoughLinesTitle: "Không đủ line",
    notEnoughLinesDetail: "Cần ít nhất 2 line để sao chép.",
    noSourceLineTitle: "Không tìm thấy line nguồn",
    noSourceLineDetail: "Line nguồn không tồn tại.",
    sourceNoMachinesTitle: "Line nguồn trống",
    sourceNoMachinesDetail: "Không có máy nào để sao chép.",
    noTargetLineTitle: "Chưa chọn line đích",
    noTargetLineDetail: "Vui lòng chọn ít nhất 1 line đích.",
    noNewMachinesTitle: "Không có máy mới",
    noNewMachinesDetail: "Không có máy nào được sao chép.",
    copySuccessTitle: "Sao chép thành công",
    copyIncompleteTitle: "Sao chép không đầy đủ",
    deleteLineSuccessTitle: "Xóa line thành công",
    deleteMachineSuccessTitle: "Xóa máy thành công",
    deleteLineFailTitle: "Lỗi xóa line",
    deleteMachineFailTitle: "Lỗi xóa máy",
    deleteFailDetail: "Có lỗi xảy ra khi xóa."
  }
};

fs.writeFileSync(path, JSON.stringify(viData, null, 2), 'utf8');
console.log('vi.json updated!');
